### ISSUE TITLE
Clarification re: ccw and cw impeller

### ISSUE THREAD

**Issue by coryalder** [scheffield/stencil-fix-portable#2]
Hi! Love this design - I was just about to print the shop-vac version of this when I found your most recent video!

Just wondering if you could clarify the meaning of the CCW and CW impeller models. It doesn't look like I need both, which should I print, and when?

**Comment by scheffield** [comment]
Hey there. I'm glad you find it useful 😄 .

CW standards for clockwise and CCW for counter clockwise. So print what ever direction your motor spins in.

**Comment by analogmonster** [comment]
Just wanted to add, you can change the direction an ESC drives a motor by swapping 2 of the 3 wires between the ESC and motor.  But best practice would be to print an impeller according to what direction the thread is cut on the motor.  You want the motor to spin the direction that would tighten the impeller onto the shaft, otherwise the motor could eventually unthread the impeller just through torque
